version: '3.8'

services:
  portal:
    env_file:
      - .env
    image: yasmany/portal:latest
    depends_on:
      - gateway
      - keycloak

  rabbitmq:
    env_file:
      - .env
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  omnisdb:
    env_file:
      - .env
    image: 'mongo:6.0.2-focal'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - omnisdb-data:/data/db

  gateway:
    env_file:
      - .env
    image: yasmany/gateway:latest
    depends_on:
      - rabbitmq

  signal:
    env_file:
      - .env
    image: yasmany/signal:latest
    depends_on:
      - rabbitmq
      - omnisdb

  meetings:
    env_file:
      - .env
    image: yasmany/meetings:latest
    depends_on:
      - rabbitmq
      - omnisdb

  recruitment:
    env_file:
      - .env
    image: yasmany/recruitment:latest
    depends_on:
      - rabbitmq
      - omnisdb

  postgres:
    env_file:
      - .env
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    env_file:
      - .env
    image: quay.io/keycloak/keycloak:legacy
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8082:8080
    depends_on:
      - postgres

volumes:
  omnisdb-data:
  postgres_data:
