version: '3.8'

services:
  portal:
    env_file:
      - .env
    build:
      context: ./portal
      target: development
    restart: always
    ports:
      - ${OMNIS_PORT}:3000
    environment:
      NODE_ENV: development
    stdin_open: true
    volumes:
      - ./portal:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  rabbitmq:
    env_file:
      - .env

  omnisdb:
    env_file:
      - .env

  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 8081:3000
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      CONNECTIONS: con1

      LABEL_con1: MongoDB
      URL_con1: ${MONGO_DSN}
      ENGINE_con1: mongo@dbgate-plugin-mongo

  gateway:
    env_file:
      - .env
    build:
      context: ./gateway
      target: development
    restart: always
    ports:
      - ${GATEWAY_PORT}:3000
      - 9229:9229
    environment:
      NODE_ENV: development
    stdin_open: true
    volumes:
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules

  meetings:
    env_file:
      - .env
    build:
      context: ./meetings
      target: development
    ports:
      - 9230:9229
    restart: always
    stdin_open: true
    environment:
      NODE_ENV: development
    volumes:
      - ./meetings:/usr/src/app
      - /usr/src/app/node_modules

  signal:
    env_file:
      - .env
    build:
      context: ./signal
      target: development
    ports:
      - ${SIGNAL_PORT}:3000
      - 9231:9229
    restart: always
    stdin_open: true
    volumes:
      - ./signal:/usr/src/app
      - /usr/src/app/node_modules

  recruitment:
    env_file:
      - .env
    build:
      context: ./recruitment
      target: development
    ports:
      - 9232:9229
    restart: always
    stdin_open: true
    environment:
      NODE_ENV: development
    volumes:
      - ./recruitment:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    env_file:
      - .env

  keycloak:
    env_file:
      - .env

volumes:
  dbgate-data:
