name: Environment Demo Prod
on: 
  workflow_dispatch:
    inputs:
      env_deploy:
        description: 'Environment to deploy'
        required: false
        default: 'demo-prod'

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: SSH into remote machine and execute command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 200m
        script: |
          cd code/omnis/scripts
          ./restore.sh ~/code/omnis/environments/${{ github.event.inputs.env_deploy }}
          cd ..
          docker compose restart