name: Build and Deploy Omnis
on: [workflow_dispatch]

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into remote machine and execute command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 200m
        script: |
          mkdir code
          cd code
          git clone git@github.com:yasmanymd/omnis.git
          cd omnis
          sudo docker compose -f docker-compose.yaml -f docker-compose.prod.build.yaml build
          sudo docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d